// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 51102e4ab212e66d90d93ce57fb718af35ea5a7207f1c747b1ba3ca57940c725

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "educa-keycloak-tema";

export const themeNames: ThemeName[] = ["educa-keycloak-tema"];

export type KcEnvName = "FDN_THEME_PRIMARY_COLOR" | "FDN_THEME_SECONDARY_COLOR";

export const kcEnvNames: KcEnvName[] = [
    "FDN_THEME_PRIMARY_COLOR",
    "FDN_THEME_SECONDARY_COLOR"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    FDN_THEME_PRIMARY_COLOR: "#1976d2",
    FDN_THEME_SECONDARY_COLOR: "#9c27b0"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
